--- #YAML:1.0
name:                UMLS-Interface
version:             0.41
abstract:            Perl interface to the Unified Medical Language System (UMLS)
license:             ~
author:              
    - Bridget McInnes <bthomson@cs.umn.edu>, Ted Pedersen <tpederse@d.umn.edu>, Serguei Pakhomov <pakh0002@umn.edu>, Siddharth Patwardhan <sidd@cs.utah.edu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    bignum:                        0
    DBD::mysql:                    0
    DBI:                           0
    Digest::SHA1:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
