--- #YAML:1.0
name:               UMLS-Interface
version:            1.17
abstract:           Perl interface to the Unified Medical Language System (UMLS)
author:
    - Bridget McInnes <bthomson@cs.umn.edu>, Ted Pedersen <tpederse@d.umn.edu>, Serguei Pakhomov <pakh0002@umn.edu>, Siddharth Patwardhan <sidd@cs.utah.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::mysql:    0
    DBI:           0
    Digest::SHA1:  2.12
    File::Path:    2.08
    File::Spec:    3.31
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
